name: actionable
on:
  workflow_dispatch:
    inputs:
      repo:
        description: "repo"
        required: true
      number:
        description: "PR or issue number that is now actionable"
        required: true

jobs:
  sync:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install ghapi
        run: pip install -r requirements.txt
      - name: Sync
        run: python .github/scripts/actionable.py ${{ github.event.inputs.repo }} ${{ github.event.inputs.number }}
        env:
          CONTEXT_GITHUB: ${{ toJson(github) }}
