name: bucket
on:
  workflow_dispatch:
    inputs:
      repo:
        description: "repo"
        required: true
      number:
        description: "PR or issue number to bucket"
        required: true

jobs:
  sync:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install PyGithub
        run: pip install PyGithub
      - name: Ad to bucket
        run: python .github/scripts/add_bucket.py ${{ github.event.inputs.repo }} ${{ github.event.inputs.number }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
