name: create
on:
  workflow_dispatch:
    inputs:
      repo:
        description: "repo"
        required: true

jobs:
  sync:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install ghapi
        run: pip install -r requirements.txt
      - name: Sync
        run: python .github/scripts/create_project.py ${{ github.event.inputs.repo }}
        env:
          CONTEXT_GITHUB: ${{ toJson(github) }}
