name: sync
on:
  schedule:
    - cron: "30 */2 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install ghtaskhub
        run: python setup.py develop
      - name: Sync
        run: ghtaskhub all sync
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TASKHUB_REPO: ${{ github.repository }}
